### PR TITLE
If the number of tests run does not match the number of tests compiled fail the smoke test run

### PR DESCRIPTION
**Pull request by maxcbc**
Does what it says in the tin.

Also changes some colours for the smoke test output

 🐿 v2.10.3

### CODE REVIEW

**Comment by adgad** [comment]
Interesting...what scenarios do the tests not run in?

**Comment by maxcbc** [comment]
@adgad I had a scenario earlier where the test timed out then it didn't run the following tests.
https://circleci.com/gh/Financial-Times/next-article/13536

**Comment by adgad** [comment]
Ah cool. This makes sense.

For information, there's definitely some work that needs to be done to improve error handling here. I added a really horrible thing that allows for two errors (to make tests less flaky) - but that masks actual errors. 

Hopefully if we ever get round to improving / dealing with the actual errors - this scenario shouldn't happen!

Until then, 🚢

**Comment by maxcbc** [comment]
@adgad grab us if you want a second bod to look at stuff when you do this I have some ideas for how to do it.

**Pull request merged**
